version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    networks:
      - flower-net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - SERVER_ADDRESS=http://server:8080
    networks:
      - flower-net

networks:
  flower-net:
    driver: bridge

