# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the pyproject.toml file into the container
COPY pyproject.toml ./

# Install Hatch
RUN pip install hatch

# Install the dependencies
RUN hatch env create

RUN pip install flwr


# Copy the rest of the application code into the container
COPY . .

CMD ["flwr", "run", "my_app/server_app.py"]
